name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ln -s Makefile.Linux Makefile
    - name: make
      run: make
